# Generated by Django 4.2.7 on 2025-11-28 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("VOICE", "Voice")],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                (
                    "problem_text",
                    models.TextField(
                        help_text="The problem description (from text input or transcribed from voice)"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Voice recording file (if input_type is VOICE)",
                        null=True,
                        upload_to="problem_audio/",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="AI-generated recommendations as a list of solutions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem Report",
                "verbose_name_plural": "Problem Reports",
                "db_table": "problem_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="problem_rep_user_id_89c70b_idx",
                    ),
                    models.Index(
                        fields=["input_type"], name="problem_rep_input_t_268b09_idx"
                    ),
                ],
            },
        ),
    ]
